list: $/blazcigale/restaurantmenu/models/item/columns.yaml
modelClass: BlazCigale\RestaurantMenu\Models\Item
title: Items
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'blazcigale/restaurantmenu/items/update/:id'
