name: Items
form: $/sikhub/restaurantmenu/models/item/fields.yaml
modelClass: Sikhub\RestaurantMenu\Models\Item
defaultRedirect: sikhub/restaurantmenu/items
create:
    redirect: 'sikhub/restaurantmenu/items/update/:id'
    redirectClose: sikhub/restaurantmenu/items
update:
    redirect: sikhub/restaurantmenu/items
    redirectClose: sikhub/restaurantmenu/items
