name: Items
form: $/blazcigale/restaurantmenu/models/item/fields.yaml
modelClass: BlazCigale\RestaurantMenu\Models\Item
defaultRedirect: blazcigale/restaurantmenu/items
create:
    redirect: 'blazcigale/restaurantmenu/items/update/:id'
    redirectClose: blazcigale/restaurantmenu/items
update:
    redirect: blazcigale/restaurantmenu/items
    redirectClose: blazcigale/restaurantmenu/items
