list: $/blazcigale/restaurantmenu/models/dailyoffer/columns.yaml
modelClass: BlazCigale\RestaurantMenu\Models\DailyOffer
title: DailyOffers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'blazcigale/restaurantmenu/dailyoffers/update/:id'
