plugin:
    name: 'blazcigale.restaurantmenu::lang.plugin.name'
    description: 'blazcigale.restaurantmenu::lang.plugin.description'
    author: BlazCigale
    icon: oc-icon-book
    homepage: 'https://github.com/blazcigale/october-plugin-restaurant-menu'
navigation:
    blazcigale-menu:
        label: 'blazcigale.restaurantmenu::lang.menu.menu'
        url: blazcigale/restaurantmenu/items
        icon: icon-book
        permissions:
            - can_edit_items
        sideMenu:
            blazcigale-items:
                label: 'blazcigale.restaurantmenu::lang.menu.items'
                url: blazcigale/restaurantmenu/items
                icon: icon-sitemap
                permissions:
                    - can_edit_items
            blazcigale-sections:
                label: 'blazcigale.restaurantmenu::lang.menu.sections'
                url: blazcigale/restaurantmenu/sections
                icon: icon-certificate
                permissions:
                    - can_edit_sections
            blazcigale-allergens:
                label: 'blazcigale.restaurantmenu::lang.menu.allergens'
                url: blazcigale/restaurantmenu/allergens
                icon: icon-bug
