list: $/sikhub/restaurantmenu/models/allergen/columns.yaml
modelClass: Sikhub\RestaurantMenu\Models\Allergen
title: Allergens
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sikhub/restaurantmenu/allergens/update/:id'
