name: Allergens
form: $/blazcigale/restaurantmenu/models/allergen/fields.yaml
modelClass: BlazCigale\RestaurantMenu\Models\Allergen
defaultRedirect: blazcigale/restaurantmenu/allergens
create:
    redirect: 'blazcigale/restaurantmenu/allergens/update/:id'
    redirectClose: blazcigale/restaurantmenu/allergens
update:
    redirect: blazcigale/restaurantmenu/allergens
    redirectClose: blazcigale/restaurantmenu/allergens
