name: Sections
form: $/blazcigale/restaurantmenu/models/section/fields.yaml
modelClass: BlazCigale\RestaurantMenu\Models\Section
defaultRedirect: blazcigale/restaurantmenu/sections
create:
    redirect: 'blazcigale/restaurantmenu/sections/update/:id'
    redirectClose: blazcigale/restaurantmenu/sections
update:
    redirect: blazcigale/restaurantmenu/sections
    redirectClose: blazcigale/restaurantmenu/sections
