list: $/blazcigale/restaurantmenu/models/section/columns.yaml
modelClass: BlazCigale\RestaurantMenu\Models\Section
title: Sections
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'blazcigale/restaurantmenu/sections/update/:id'
